apiVersion: v1
kind: Service
metadata:
  name: nrp
  labels:
    app: nrp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    app: nrp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrp
  template:
    metadata:
      labels:
        app: nrp
    spec:
      containers:
        - name: nrp
          image: rifqifatih/nrp
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: nrp-models
            mountPath: /home/bbpnrsoa/nrp/src/Models
            subPath: Models
          - name: nrp-experiments
            mountPath: /home/bbpnrsoa/nrp/src/Experiments
            subPath: Experiments
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nrp-frontend
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: init-nrp-models
        image: k8s.gcr.io/git-sync:v3.1.3
        volumeMounts:
        - mountPath: /tmp/git
          name: nrp-models
        env:
        - name: GIT_SYNC_REPO
          value: https://bitbucket.org/hbpneurorobotics/Models.git
        - name: GIT_SYNC_BRANCH
          value: master18
        - name: GIT_SYNC_DEST
          value: "Models"
        - name: GIT_SYNC_TIMEOUT
          value: "600"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
      - name: init-nrp-experiments
        image: k8s.gcr.io/git-sync:v3.1.3
        volumeMounts:
        - mountPath: /tmp/git
          name: nrp-experiments
        env:
        - name: GIT_SYNC_REPO
          value: https://bitbucket.org/hbpneurorobotics/Experiments.git
        - name: GIT_SYNC_BRANCH
          value: master18
        - name: GIT_SYNC_DEST
          value: "Experiments"
        - name: GIT_SYNC_TIMEOUT
          value: "600"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
      volumes:
      - name: nrp-models
        emptyDir: {}
      - name: nrp-experiments
        emptyDir: {}
      - name: nrp-user-data
        hostPath:
          path: /home/bbpnrsoa/.opt/nrpStorage