apiVersion: v1
kind: Service
metadata:
  name: nrp
  labels:
    app: nrp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: nrp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrp
  template:
    metadata:
      labels:
        app: nrp
    spec:
      containers:
        - name: nrp
          image: rifqifatih/nrp
          imagePullPolicy: Always
          ports:
          - containerPort: 8080